Rails.application.routes.draw do
  # generated by under_construction gem
  resources 'under_construction_email_storage', only: :create
  resources 'under_construction', only: :index

  root to: 'visitors#index'

  # generated by under_construction gem
  match "/*other" => redirect("/under_construction"), via: :all
end
